.TH REMOVE_MEMBERS 8 2001-03-10
.SH NAME
remove_members \- Remove members from a list.

.SH SYNOPSIS
remove_members [options] listname [addr1 ...]

.SH OPTIONS

.PP
\fB\-f\fB \fIfile\fI, \fB\-\-file\fB=\fIfile\fI
Remove member addresses found in the given file.  If file is
`-', read stdin.

\fB\-a\fB, \fB\-\-all\fB
Remove all members of the mailing list.

\fB\-h\fB, \fB\-\-help\fB
Print a small help text and exit
.PP

listname is the name of the mailing list to use.

addr1 ... are additional addresses to remove.

.SH AUTHOR
Author of Mailman is the Mailman Cabal, see http://www.list.org/ for
information.  This manpage is written by Tollef Fog Heen
<tfheen@debian.org> for Debian

.SH SEE ALSO
Mailman documentation on http://www.list.org/ and in
/usr/share/doc/mailman.
